version: '2.1'

services:

  prometheus:
    image: prom/prometheus:v2.38.0
    network_mode: "bridge"
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "127.0.0.1:9090:9090"
    restart: always

  grafana:
    image: grafana/grafana-oss:9.1.4
    user: "$UID:$GID"
    network_mode: "bridge"
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost