scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['172.20.102.43:8080']
        labels:
          application: 'My Spring Boot Application'